server:
  port: 8080

spring:
  thymeleaf:
    mode: HTML
    cache: false
    enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入


mybatis:
  type-aliases-package: com.hj.blog.mapper
  mapper-locations: classpath:mapper/*Mapper.xml

#logging:
  #evel:
    #root: info

logging:
  level:
    root: info
  file:
    path: log/blog.log

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
